channels:
  - conda-forge
dependencies:
  - python=3.12
  - napari
  - pyqt
  - scikit-image
  - numpy
  - scipy
  - matplotlib
  - pillow
  - tifffile
  - pandas
  - jupyterlab
  - ipywidgets
  # Required for desktop view on mybinder.org
  - websockify
  - pip
  - pip:
    - jupyter-remote-desktop-proxy